version: '3'

services:
  count-down:
    image: count-down
    hostname: count-down
    build:
      context: ./count-down
      dockerfile: Dockerfile
    container_name: count-down
    ports:
      - "8090:8080"

  file-sharer:
    image: file-sharer
    hostname: file-sharer
    build:
      context: ./apache2-container
      dockerfile: Dockerfile
    container_name: file-sharer
    ports:
      - "8091:80"
    volumes:
        - /home/pi/Share:/var/www/listing

  virtual-piano:
    image: virtual-piano
    hostname: virtual-piano
    build:
      context: ./virtualPiano
      dockerfile: Dockerfile
    container_name: virtual-piano
    ports:
      - "8092:8080"

  ric-script:
    image: ric-script
    hostname: ric-script
    build:
      context: ./ric-script
      dockerfile: Dockerfile
    container_name: ric-script
    ports:
      - "8093:3000"
    restart: always

  reverse:
    container_name: reverse
    hostname: reverse
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80



