version: '3'

services:
  count-down:
    image: count-down
    hostname: count-down
    build:
      context: ./count-down
      dockerfile: Dockerfile
    container_name: count-down
    ports:
      - "8090:8080"

  file-sharer:
    image: file-sharer
    hostname: file-sharer
    build:
      context: ./apache2-container
      dockerfile: Dockerfile
    container_name: file-sharer
    ports:
      - "8091:80"
    volumes:
        - /media/pi/Seagate Expansion Drive/Share:/var/www/listing

  virtual-piano:
    image: virtual-piano
    hostname: virtual-piano
    build:
      context: ./virtualPiano
      dockerfile: Dockerfile
    container_name: virtual-piano
    ports:
      - "8092:8080"

  reverse:
    container_name: reverse
    hostname: reverse
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80


  brfrynninge:
    container_name: brfrynninge
    hostname: brfrynninge
    build:
      context: brf
      dockerfile: Dockerfile
    volumes:
      - ./brf/site:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - db
    environment:
      MYSQL_HOST: db:3306
      MYSQL_USER: myusr
      MYSQL_PASSWORD: pass
      MYSQL_DB: mydb

  db:
    container_name: db
    image: jsurf/rpi-mariadb
    volumes:
      - ./brf/brfrynninge.sql:/docker-entrypoint-initdb.d/data.sql
      - ./brf/my.cnf:/etc/mysql/conf.d/my.cnf
#      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myusr
      MYSQL_PASSWORD: pass

