version: '3'

services:
  count-down:
    image: count-down
    build:
      context: ./count-down
      dockerfile: Dockerfile
    container_name: count-down
    ports:
      - "8090:8080"

  file-sharer:
    image: file-sharer
    build:
      context: ./apache2-container
      dockerfile: Dockerfile
    container_name: file-sharer
    ports:
      - "8091:8080"
    volumes:
        - /home/pi/Share:/var/wwww

  virtual-piano:
    image: virtual-piano
    build:
      context: ./virtualPiano
      dockerfile: Dockerfile
    container_name: virtual-piano
    ports:
      - "8092:8080"

  ric-script:
    image: ric-script
    build:
      context: ./ric-script
      dockerfile: Dockerfile
    container_name: ric-script
    ports:
      - "8093:3000"



